version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "5050:5050"
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
