name: Backend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"
      - run: cd backend && npm install
      - run: cd backend && npm test
      - run: cd backend && npm run build

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-west-2"

      - name: Package Application
        run: |
          cd backend
          zip -r ../backend.zip .

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name minimal-mern-lambda-function --zip-file fileb://backend.zip
